# fly.toml app configuration file generated for demo-12345 on 2024-01-15T19:36:54+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "demo-12345"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[[services]]
  protocol = "tcp"
  internal_port = 80

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "30s"
    method = "get"
    path = "/"
    protocol = "http"
    tls_skip_verify = false

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
