name: Main branch Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    name: Demo App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: ${{ secrets.PAT_TOKEN }}
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -c ${{ github.workspace }}/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} 